import type {Metadata} from 'next';

import NavMenu from '@/components/nav-menu';

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'My Portfolio generated by create next app'
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <main className="dark flex flex-col text-white h-[100vh] bg-slate-950">
      <div className="bg-slate-950 h-4" />
      <div className="flex h-full">
        <NavMenu />
        <div className="w-full rounded-md bg-slate-900">{children}</div>
      </div>
    </main>
  );
}
